import AdminComponent from "./main";

import INTERFACE_CONTROLE_ALARMES from "./alarmes";
import INTERFACE_CONTROLE_ESTACOES from "./estacoes";
import INTERFACE_CONTROLE_USUARIOS from "./usuarios";
import INTERFACE_CONTROLE_PARAMETROS from "./tipoParametro";
import INTERFACE_CONFIGURAR_ALARMES from "./alarmes/Funcionalidades/ConfigurarAlarme";
import INTERFACE_CONTROLE_PARAMETROSRELACIONADO from "./parametro";

export {
    AdminComponent,
    INTERFACE_CONTROLE_ALARMES,
    INTERFACE_CONTROLE_ESTACOES,
    INTERFACE_CONTROLE_PARAMETROS,
    INTERFACE_CONTROLE_USUARIOS,
    INTERFACE_CONFIGURAR_ALARMES,
    INTERFACE_CONTROLE_PARAMETROSRELACIONADO

}

