name: CI development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
   build-e-teste:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  

    - name: Entrar na pasta do projeto
      run: cd seth
      
    - name: Instalar Dependências
      run: npm install

    - name: Rodar Testes
      run: npm test

    - name: Buildar Projeto
      run: npm run build


      
