name: CI development

on:
  push:
    branches:
      - development
      - Fix/*
      - Feat/*
  pull_request:
    branches:
      - main

jobs:
   build-e-teste:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  

    - name: Instalar Dependências
      run: |
        cd seth
        npm install

    - name: Buildar Projeto
      run: |
        cd seth
        npm run build
    
    - name: Rodar Testes
      run: |
        # Extração  do nome da branch
        BRANCH_NAME=${GITHUB_REF#refs/heads/}

        echo "Nome da branch: $BRANCH_NAME"
  
        # Rodando testes de integração para PRs entre 'development' e 'main'
        if [[ "$GITHUB_BASE_REF" == "main" && "$GITHUB_HEAD_REF" == "development" ]]; then
          echo "Rodando testes de integração da branch development para main"
          npm test -- __tests__/integration

        # Rodando testes para a branch 'development' (mas não deve rodar em PR)
        elif [[ "$BRANCH_NAME" == "development" ]]; then
          echo "Rodando testes para branch development"
          npm test -- __tests__/unit
  
        # Rodando testes para branches 'Fix/*' ou 'Feat/*'
        elif [[ "$BRANCH_NAME" == Feat/* ]] || [[ "$BRANCH_NAME" == Fix/* ]]; then
          FEATURE_TEST_DIR="src/__tests__/unit/tasks/${BRANCH_NAME//\//-}"
          echo "Verificando se os testes existem em: $FEATURE_TEST_DIR"
            
          # Verifica se o diretório de testes da feature existe
          if [ -d "$FEATURE_TEST_DIR" ]; then
            echo "Rodando testes para a branch $BRANCH_NAME em $FEATURE_TEST_DIR"
            npm test -- $FEATURE_TEST_DIR
          else
            echo "Nenhum teste foi encontrado para $BRANCH_NAME. Pulando."
          fi
        fi