name: CI development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
   build-e-teste:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  

    - name: Instalar Dependências
      run: |
        cd seth
        npm install

    - name: Buildar Projeto
      run: |
        cd seth
        npm run build